Feature/tasks
helmq/task-manager pull request #21
Opened 2019-05-05 08:23 UTC by helmq

2019-05-13 12:19 UTC, Andrew8xx8 requested changes

2019-05-13 12:19 UTC, Andrew8xx8 commented on app/javascript/packs/components/EditPopup.jsx
> +      if (e.response) {
Нужно вынести обработку ошибок в отдельный метод

2019-05-13 12:19 UTC, Andrew8xx8 commented on app/javascript/packs/components/EditPopup.jsx
> +      <>
Пустые скобки?

2019-05-13 12:19 UTC, Andrew8xx8 commented on app/javascript/packs/components/EditPopup.jsx
> +        <Modal show={show} onHide={onClose}>
Вынеси в отдельный компонент

2019-05-13 12:19 UTC, Andrew8xx8 commented on app/javascript/packs/components/EditPopup.jsx
> +  cardId: '1',
Почему cardId: 1 по дефолту? Зачем так нужно?
Зачем onClose пустой метод? Это свойство должно быть обязательным, если его не передали — компонент безсмысленен

2019-05-13 12:19 UTC, Andrew8xx8 commented on app/javascript/packs/components/FormPopup.jsx
> +        <Form.Group controlId="formDescriptionName">
Рендер контрола стоит вынести в отдельный компонент и переиспользовать

2019-05-13 12:19 UTC, Andrew8xx8 commented on app/javascript/packs/components/TaskBoard.jsx
> +      if (e.response) {
Здесь тоже обработку ошибок вынести в отдельный метод

2019-05-14 09:55 UTC, helmq commented on app/javascript/packs/components/EditPopup.jsx
> +      <>
Шорткат для <React.Fragment> (https://reactjs.org/docs/fragments.html#short-syntax), использовал чтобы вернуть группу элементов без оборачивания в div, span, etc.

2019-05-14 15:46 UTC, Andrew8xx8 approved these changes

2019-05-15 03:45 UTC, merged